<?php

  // Copyright 2009 Scalable Computing Experts
  // Author: Tom Clegg

require_once (dirname(dirname(dirname(__FILE__)))."/textile-2.0.0/classTextile.php");
require_once ("lib/oddsratio.php");

$gTheTextile = new Textile;
$gDisableEditing = FALSE;

function editable($id, $content, $title="", $options=false)
{
  global $gDisableEditing;
  global $gTheTextile;

  if (ereg ('__oddsratio$', $id))
    return editable_oddsratio ($id, $content, $title, $options);
  else if (ereg ('__f_variant_quality', $id))
    return editable_quality ($id, $content, $title, $options);
  else {
    /*
    if ($options &&
	is_array ($options["select_options"]) &&
	array_key_exists ($content, $options["select_options"]))
      $html = "<P>".$options["select_options"][$content]."</P>";
    else
    */
    $html = $gTheTextile->textileRestricted ($content);

    if (trim($html) == "") $html = "<P>&nbsp;</P>";

    if (strlen($title) < 60 && !preg_match ('{<(b|strong)\b}i', $title))
      $title = "<strong>$title</strong>";
  }

  $html = "<DIV id=\"toolbar_$id\" class=\"toolbar\">"
    . "<P class=\"toolbar_title\">$title</P></DIV>"
    . "<SPAN id=\"preview_$id\">"
    . $html
    . "</SPAN>";

  if ($gDisableEditing || !getCurrentUser())
    return $html;

  $selector = "";
  if ($options && is_array($options["select_options"])) {
    $selector = "<P style=\"display:none;\"><SELECT id=\"edited_$id\" name=\"edited_$id\" onchange=\"editable_check_unsaved(this); editable_save();\">\n";
    foreach ($options["select_options"] as $k => $v) {
      $selected = ($content == $k) ? " selected" : "";
      $selector .= "<OPTION value=\"".htmlentities($k)."\"$selected>".htmlspecialchars($v)."</OPTION>\n";
    }
    $selector .= "</SELECT></P>";
  }
  return ("<SPAN id=\"$id\" class=\"editable\">" .
	  (strlen($options["tip"]) ? "<P class=\"csshide\" id=\"tip_$id\">$options[tip]</P>" : "") .
	  $html .
	  $selector .
	  "<INPUT type=\"hidden\" id=\"orig_$id\" value=\"".htmlentities($content)."\"/>" .
	  "</SPAN>");
}

function editable_oddsratio ($id, $content, $title, $options)
{
  global $gDisableEditing;
  $editable = !$gDisableEditing && getCurrentUser();

  $html = "";
  if ($content == "")
    $figs = array();
  else
    $figs = json_decode ($content, true);
  $trclass = ($options["rownumber"] % 4 < 2) ? " class=\"altcolor\"" : "";
  $html .= "<TR$trclass>";
  $html .= "<TD class=\"rowlabel\">$title</TD>";
  $empty = 1;
  foreach (array ("case_pos", "case_neg", "control_pos", "control_neg") as $x) {
    $cellid = "{$id}__o_{$x}__";
    if (!isset ($figs[$x]) || !strlen ($figs[$x])) {
      if (!$editable)
	$figs[$x] = "-";
    }
    else {
      $empty = 0;
      $figs[$x] = $figs[$x] + 0;
    }

    $cell = $figs[$x];
    if ($editable) {
      $html .= "<TD id=\"$cellid\" class=\"editable clicktoedit\"><SPAN id=\"preview_$cellid\">{$cell}</SPAN><INPUT type=\"hidden\" id=\"orig_$cellid\" name=\"orig_$cellid\" value=\"".htmlentities($figs[$x])."\"/></TD>\n";
    }
    else {
      $html .= "<TD>{$cell}</TD>\n";
    }
  }
  $OR = oddsratio_compute($figs, true);
  if ($OR != "-") $OR = "<STRONG>$OR</STRONG>";
  $html .= "<TD>$OR</TD>\n";
  $html .= "</TR>\n";
  if ($empty && !$editable) return "";
  return $html;
}

$gQualityAxes = array ("Computational" => "Average of predictions generated by SFIT, PolyPhen, and NBLOSUM",
		       "Molecular and cellular" => "Results of experiments involving enzyme extracts, cell lines and animal models",
		       "Clinical population" => "Odds ratio",
		       "Clinical family" => "LOD score",
		       "Clinical outcomes" => "The quality of studies investigating the effectiveness of action based on the described impact of this mutation given a specific phenotype/family history");

function editable_quality ($id, $content, $title, $options)
{
    global $gDisableEditing;
    $editable = !$gDisableEditing && getCurrentUser();

    $html = "<TABLE class=\"quality_table\">\n";
    $html .= "<TR><TH class=\"rowlabel\">Variant quality</TH><TH></TH><TH width=\"16\"></TH><TH></TH><TH width=\"*\"></TH></TR>\n";
    $axis_index = 0;
    global $gQualityAxes;
    foreach ($gQualityAxes as $axis => $desc) {
	if (strlen($content) <= $axis_index)
	    $score = "-";
	else {
	    $score = substr($content, $axis_index, 1);
	    if (!ereg ('^[0-5]$', $score))
		$score = "-";
	}

	$html .= "<TR>\n";
	$html .= "<TD class=\"rowlabel\"><SPAN onmouseover=\"Tip('$desc',BALLOON,true,FIX,[this,0,0],FOLLOWMOUSE,false,ABOVE,true);\" onmouseout=\"UnTip();\">$axis</SPAN></TD>\n";

	$cellid = "{$id}__o_{$axis_index}__";

	$cancel_cell = "";
	$stars = "";
	for ($i=($editable ? -1 : 1); $i<=5; $i++) {
	    $attrs = "width=\"16\" height=\"16\" alt=\"\"";
	    if ($editable)
		$attrs .= " onclick=\"editable_5star_click('{$cellid}',$i);\"";
	    if ($i > 0)
		$attrs .= " id=\"star{$i}_{$cellid}\"";

	    if ($i == -1)
		$stars .= "<SPAN $attrs class=\"halfthere x\">&times;</SPAN>";
	    else {
		if ($i == 0 || $score == "-")
		    $attrs .= " class=\"halfthere\"";

		if ($i > 0 && $i <= $score)
		    $stars .= "<IMG src=\"/img/star-blue16.png\" $attrs>";
		else
		    $stars .= "<IMG src=\"/img/star-white16.png\" $attrs>";
	    }

	    if ($i == -1) {
		// Show the "X" (null) button last, although I made it first
		$cancel_cell = $stars;
		$stars = "";
	    }
	}
	$html .= "<TD>$stars</TD>\n";

	if ($editable) {
	    $html .= "<TD id=\"$cellid\" class=\"editable 5star\"><SPAN id=\"preview_$cellid\">{$score}</SPAN><INPUT type=\"hidden\" id=\"orig_$cellid\" name=\"orig_$cellid\" value=\"".htmlentities($score)."\"/></TD><TD>{$cancel_cell}</TD>\n";
	}
	else if ($score)
	    $html .= "<TD>$score</TD>\n";
	else
	    $html .= "<TD></TD>\n";

	if ($axis_index == 0)
	    $html .= "<TD><SPAN class=\"halfthere\">(This column soon to collect/display justification for ratings)</SPAN></TD>";
	else
	    $html .= "<TD></TD>\n";

	$html .= "</TR>\n";
	++$axis_index;
    }

    $html .= "</TABLE><P>&nbsp;</P>\n";

    return $html;
}

?>
