/* Generated by Pyrex 0.9.8.4 on Wed Aug 20 17:50:30 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "ctype.h"
#include "string.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from _twobit */


/* Declarations from implementation of _twobit */

static char *__pyx_v_7_twobit_valToNt;

static char __pyx_k1[] = "seek";
static char __pyx_k2[] = "sequence_offset";
static char __pyx_k3[] = "read";
static char __pyx_k4[] = "n_block_starts";
static char __pyx_k5[] = "bisect";
static char __pyx_k6[] = "n_block_sizes";
static char __pyx_k7[] = "N";
static char __pyx_k8[] = "masked_block_starts";
static char __pyx_k9[] = "masked_block_sizes";
static char __pyx_k10[] = "struct";
static char __pyx_k11[] = "sys";
static char __pyx_k12[] = "TCAG";

static PyObject *__pyx_n_bisect;
static PyObject *__pyx_n_masked_block_sizes;
static PyObject *__pyx_n_masked_block_starts;
static PyObject *__pyx_n_n_block_sizes;
static PyObject *__pyx_n_n_block_starts;
static PyObject *__pyx_n_read;
static PyObject *__pyx_n_seek;
static PyObject *__pyx_n_sequence_offset;
static PyObject *__pyx_n_struct;
static PyObject *__pyx_n_sys;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_bisect, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_masked_block_sizes, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_masked_block_starts, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_n_block_sizes, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_n_block_starts, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_read, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_seek, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_sequence_offset, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_struct, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_sys, 1, __pyx_k11, sizeof(__pyx_k11)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;


/* Implementation of _twobit */

static PyObject *__pyx_f_7_twobit_read(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7_twobit_read[] = "\n    Stolen directly from Jim Kent\'s twoBit.c\n    ";
static PyObject *__pyx_f_7_twobit_read(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_file = 0;
  PyObject *__pyx_v_seq = 0;
  int __pyx_v_fragStart;
  int __pyx_v_fragEnd;
  PyObject *__pyx_v_do_mask = 0;
  int __pyx_v_packedStart;
  int __pyx_v_packedEnd;
  int __pyx_v_packByteCount;
  int __pyx_v_pOff;
  int __pyx_v_pStart;
  int __pyx_v_pEnd;
  int __pyx_v_midStart;
  int __pyx_v_remainder;
  int __pyx_v_partCount;
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_v_s;
  int __pyx_v_e;
  char *__pyx_v_packed;
  char *__pyx_v_dna;
  char __pyx_v_partial;
  PyObject *__pyx_v_dna_py;
  PyObject *__pyx_v_packed_py;
  PyObject *__pyx_v_midEnd;
  PyObject *__pyx_v_n_block_count;
  PyObject *__pyx_v_start_ix;
  PyObject *__pyx_v_m_block_count;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  Py_ssize_t __pyx_6;
  long __pyx_7;
  long __pyx_8;
  static char *__pyx_argnames[] = {"file","seq","fragStart","fragEnd","do_mask",0};
  __pyx_v_do_mask = __pyx_d1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOii|O", __pyx_argnames, &__pyx_v_file, &__pyx_v_seq, &__pyx_v_fragStart, &__pyx_v_fragEnd, &__pyx_v_do_mask)) return 0;
  Py_INCREF(__pyx_v_file);
  Py_INCREF(__pyx_v_seq);
  Py_INCREF(__pyx_v_do_mask);
  __pyx_v_dna_py = Py_None; Py_INCREF(Py_None);
  __pyx_v_packed_py = Py_None; Py_INCREF(Py_None);
  __pyx_v_midEnd = Py_None; Py_INCREF(Py_None);
  __pyx_v_n_block_count = Py_None; Py_INCREF(Py_None);
  __pyx_v_start_ix = Py_None; Py_INCREF(Py_None);
  __pyx_v_m_block_count = Py_None; Py_INCREF(Py_None);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":36 */
  __pyx_v_packedStart = (__pyx_v_fragStart >> 2);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":37 */
  __pyx_v_packedEnd = ((__pyx_v_fragEnd + 3) >> 2);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":38 */
  __pyx_v_packByteCount = (__pyx_v_packedEnd - __pyx_v_packedStart);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":40 */
  __pyx_1 = PyString_FromStringAndSize(NULL,(__pyx_v_fragEnd - __pyx_v_fragStart)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_v_dna_py);
  __pyx_v_dna_py = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":41 */
  __pyx_v_dna = PyString_AsString(__pyx_v_dna_py);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":43 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_file, __pyx_n_seek); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_sequence_offset); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_packedStart); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_4 = PyNumber_Add(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":44 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_file, __pyx_n_read); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_v_packByteCount); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_packed_py);
  __pyx_v_packed_py = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":45 */
  __pyx_v_packed = PyString_AsString(__pyx_v_packed_py);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":47 */
  __pyx_5 = (__pyx_v_packByteCount == 1);
  if (__pyx_5) {

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":48 */
    __pyx_v_pOff = (__pyx_v_packedStart << 2);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":49 */
    __pyx_v_pStart = (__pyx_v_fragStart - __pyx_v_pOff);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":50 */
    __pyx_v_pEnd = (__pyx_v_fragEnd - __pyx_v_pOff);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":51 */
    __pyx_v_partial = (__pyx_v_packed[0]);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":52 */
    #ifndef PYREX_WITHOUT_ASSERTIONS
    if (!(__pyx_v_pEnd <= 4)) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    }
    #endif

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":53 */
    #ifndef PYREX_WITHOUT_ASSERTIONS
    if (!(__pyx_v_pStart >= 0)) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    }
    #endif

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":54 */
    for (__pyx_v_i = __pyx_v_pStart; __pyx_v_i < __pyx_v_pEnd; ++__pyx_v_i) {

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":55 */
      (__pyx_v_dna[0]) = (__pyx_v_7_twobit_valToNt[((__pyx_v_partial >> ((6 - __pyx_v_i) - __pyx_v_i)) & 3)]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":56 */
      __pyx_v_dna = (__pyx_v_dna + 1);
    }
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":59 */
    __pyx_v_midStart = __pyx_v_fragStart;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":60 */
    __pyx_v_remainder = (__pyx_v_fragStart & 3);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":61 */
    __pyx_5 = (__pyx_v_remainder > 0);
    if (__pyx_5) {

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":62 */
      __pyx_v_partial = (__pyx_v_packed[0]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":62 */
      __pyx_v_packed = (__pyx_v_packed + 1);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":63 */
      __pyx_v_partCount = (4 - __pyx_v_remainder);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":64 */
      for (__pyx_v_i = (__pyx_v_partCount - 1); __pyx_v_i >= 0; --__pyx_v_i) {

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":65 */
        (__pyx_v_dna[__pyx_v_i]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":66 */
        __pyx_v_partial = (__pyx_v_partial >> 2);
      }

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":67 */
      __pyx_v_midStart = (__pyx_v_midStart + __pyx_v_partCount);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":68 */
      __pyx_v_dna = (__pyx_v_dna + __pyx_v_partCount);
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":70 */
    __pyx_v_remainder = (__pyx_v_fragEnd & 3);

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":71 */
    __pyx_1 = PyInt_FromLong((__pyx_v_fragEnd - __pyx_v_remainder)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
    Py_DECREF(__pyx_v_midEnd);
    __pyx_v_midEnd = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":72 */
    __pyx_v_i = __pyx_v_midStart;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":73 */
    while (1) {
      __pyx_4 = PyInt_FromLong(__pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_4, __pyx_v_midEnd, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
      __pyx_5 = __pyx_5 < 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      if (!__pyx_5) break;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":74 */
      __pyx_v_partial = (__pyx_v_packed[0]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":75 */
      __pyx_v_packed = (__pyx_v_packed + 1);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":76 */
      (__pyx_v_dna[3]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":77 */
      __pyx_v_partial = (__pyx_v_partial >> 2);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":78 */
      (__pyx_v_dna[2]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":79 */
      __pyx_v_partial = (__pyx_v_partial >> 2);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":80 */
      (__pyx_v_dna[1]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":81 */
      __pyx_v_partial = (__pyx_v_partial >> 2);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":82 */
      (__pyx_v_dna[0]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":83 */
      __pyx_v_dna = (__pyx_v_dna + 4);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":85 */
      __pyx_v_i = (__pyx_v_i + 4);
    }

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":88 */
    __pyx_5 = (__pyx_v_remainder > 0);
    if (__pyx_5) {

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":89 */
      __pyx_v_partial = (__pyx_v_packed[0]);

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":90 */
      __pyx_v_partial = (__pyx_v_partial >> ((8 - __pyx_v_remainder) - __pyx_v_remainder));

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":91 */
      for (__pyx_v_i = (__pyx_v_remainder - 1); __pyx_v_i >= 0; --__pyx_v_i) {

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":92 */
        (__pyx_v_dna[__pyx_v_i]) = (__pyx_v_7_twobit_valToNt[(__pyx_v_partial & 3)]);

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":93 */
        __pyx_v_partial = (__pyx_v_partial >> 2);
      }
      goto __pyx_L10;
    }
    __pyx_L10:;
  }
  __pyx_L2:;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":95 */
  __pyx_v_dna = PyString_AsString(__pyx_v_dna_py);

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":97 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_n_block_starts); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_6 = PyObject_Length(__pyx_2); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyInt_FromSsize_t(__pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n_block_count);
  __pyx_v_n_block_count = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":98 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_n_block_count, __pyx_1, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_5 = __pyx_5 > 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_5) {

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":99 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bisect); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_n_block_starts); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_fragStart); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_1, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __pyx_4 = PyNumber_Subtract(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_start_ix);
    __pyx_v_start_ix = __pyx_4;
    __pyx_4 = 0;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":100 */
    __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_start_ix, __pyx_1, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    __pyx_5 = __pyx_5 < 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (__pyx_5) {
      __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      Py_DECREF(__pyx_v_start_ix);
      __pyx_v_start_ix = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L14;
    }
    __pyx_L14:;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":101 */
    __pyx_7 = PyInt_AsLong(__pyx_v_start_ix); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_n_block_count); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    for (__pyx_v_i = __pyx_7; __pyx_v_i < __pyx_8; ++__pyx_v_i) {

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":102 */
      __pyx_3 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_n_block_starts); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
      __pyx_4 = __Pyx_GetItemInt(__pyx_3, __pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_v_s = __pyx_5;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":103 */
      __pyx_1 = PyInt_FromLong(__pyx_v_s); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_n_block_sizes); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      __pyx_3 = __Pyx_GetItemInt(__pyx_2, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_4 = PyNumber_Add(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_v_e = __pyx_5;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":104 */
      __pyx_5 = (__pyx_v_s >= __pyx_v_fragEnd);
      if (__pyx_5) {
        goto __pyx_L16;
        goto __pyx_L17;
      }
      __pyx_L17:;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":106 */
      __pyx_5 = (__pyx_v_s < __pyx_v_fragStart);
      if (__pyx_5) {
        __pyx_v_s = __pyx_v_fragStart;
        goto __pyx_L18;
      }
      __pyx_L18:;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":108 */
      __pyx_5 = (__pyx_v_e > __pyx_v_fragEnd);
      if (__pyx_5) {
        __pyx_v_e = __pyx_v_fragEnd;
        goto __pyx_L19;
      }
      __pyx_L19:;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":110 */
      __pyx_5 = (__pyx_v_s < __pyx_v_e);
      if (__pyx_5) {
        memset(((__pyx_v_dna + __pyx_v_s) - __pyx_v_fragStart),(__pyx_k7[0]),(__pyx_v_e - __pyx_v_s));
        goto __pyx_L20;
      }
      __pyx_L20:;
    }
    __pyx_L16:;
    goto __pyx_L13;
  }
  __pyx_L13:;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":113 */
  __pyx_5 = PyObject_IsTrue(__pyx_v_do_mask); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  if (__pyx_5) {

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":114 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_masked_block_starts); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    __pyx_6 = PyObject_Length(__pyx_2); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_FromSsize_t(__pyx_6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_v_m_block_count);
    __pyx_v_m_block_count = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":115 */
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_m_block_count, __pyx_3, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    __pyx_5 = __pyx_5 > 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__pyx_5) {

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":116 */
      __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_bisect); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_masked_block_starts); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(__pyx_v_fragStart); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
      PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
      __pyx_2 = 0;
      __pyx_1 = 0;
      __pyx_2 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_4 = PyNumber_Subtract(__pyx_2, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_v_start_ix);
      __pyx_v_start_ix = __pyx_4;
      __pyx_4 = 0;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":117 */
      __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_start_ix, __pyx_3, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
      __pyx_5 = __pyx_5 < 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (__pyx_5) {
        __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
        Py_DECREF(__pyx_v_start_ix);
        __pyx_v_start_ix = __pyx_2;
        __pyx_2 = 0;
        goto __pyx_L23;
      }
      __pyx_L23:;

      /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":118 */
      __pyx_7 = PyInt_AsLong(__pyx_v_start_ix); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      __pyx_8 = PyInt_AsLong(__pyx_v_m_block_count); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      for (__pyx_v_i = __pyx_7; __pyx_v_i < __pyx_8; ++__pyx_v_i) {

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":119 */
        __pyx_1 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_masked_block_starts); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        __pyx_4 = __Pyx_GetItemInt(__pyx_1, __pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_v_s = __pyx_5;

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":120 */
        __pyx_3 = PyInt_FromLong(__pyx_v_s); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        __pyx_2 = PyObject_GetAttr(__pyx_v_seq, __pyx_n_masked_block_sizes); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        __pyx_1 = __Pyx_GetItemInt(__pyx_2, __pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        __pyx_4 = PyNumber_Add(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_v_e = __pyx_5;

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":121 */
        __pyx_5 = (__pyx_v_s >= __pyx_v_fragEnd);
        if (__pyx_5) {
          goto __pyx_L25;
          goto __pyx_L26;
        }
        __pyx_L26:;

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":123 */
        __pyx_5 = (__pyx_v_s < __pyx_v_fragStart);
        if (__pyx_5) {
          __pyx_v_s = __pyx_v_fragStart;
          goto __pyx_L27;
        }
        __pyx_L27:;

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":125 */
        __pyx_5 = (__pyx_v_e > __pyx_v_fragEnd);
        if (__pyx_5) {
          __pyx_v_e = __pyx_v_fragEnd;
          goto __pyx_L28;
        }
        __pyx_L28:;

        /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":127 */
        __pyx_5 = (__pyx_v_s < __pyx_v_e);
        if (__pyx_5) {
          for (__pyx_v_j = __pyx_v_s; __pyx_v_j < __pyx_v_e; ++__pyx_v_j) {
            (__pyx_v_dna[(__pyx_v_j - __pyx_v_fragStart)]) = tolower((__pyx_v_dna[(__pyx_v_j - __pyx_v_fragStart)]));
          }
          goto __pyx_L29;
        }
        __pyx_L29:;
      }
      __pyx_L25:;
      goto __pyx_L22;
    }
    __pyx_L22:;
    goto __pyx_L21;
  }
  __pyx_L21:;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":130 */
  Py_INCREF(__pyx_v_dna_py);
  __pyx_r = __pyx_v_dna_py;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_twobit.read");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_dna_py);
  Py_DECREF(__pyx_v_packed_py);
  Py_DECREF(__pyx_v_midEnd);
  Py_DECREF(__pyx_v_n_block_count);
  Py_DECREF(__pyx_v_start_ix);
  Py_DECREF(__pyx_v_m_block_count);
  Py_DECREF(__pyx_v_file);
  Py_DECREF(__pyx_v_seq);
  Py_DECREF(__pyx_v_do_mask);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"read", (PyCFunction)__pyx_f_7_twobit_read, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7_twobit_read},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_twobit(void); /*proto*/
PyMODINIT_FUNC init_twobit(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_twobit", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;};

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":19 */
  __pyx_1 = __Pyx_Import(__pyx_n_struct, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_struct, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":19 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":21 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_INCREF(__pyx_n_bisect);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_bisect);
  __pyx_2 = __Pyx_Import(__pyx_n_bisect, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_bisect); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_bisect, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":24 */
  __pyx_v_7_twobit_valToNt = __pyx_k12;

  /* "/Users/xwu/Desktop/trait/code/_twobit.pyx":26 */
  Py_INCREF(Py_False);
  __pyx_d1 = Py_False;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_twobit");
}

static char *__pyx_filenames[] = {
  "_twobit.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i) {
    PyTypeObject *t = o->ob_type;
    PyObject *r;
    if (t->tp_as_sequence && t->tp_as_sequence->sq_item)
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = PyInt_FromLong(i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
